//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.05.28 at 03:50:25 PM CEST 
//


package generate;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="username" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="password" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="profilepic" type="{http://www.w3.org/2001/XMLSchema}base64Binary" minOccurs="0"/>
 *         &lt;element name="realforename" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="reallastname" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="website" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="detailinfo" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "username",
    "password",
    "profilepic",
    "realforename",
    "reallastname",
    "website",
    "detailinfo"
})
@XmlRootElement(name = "Userinformation")
public class Userinformation {

    @XmlElement(required = true)
    protected String username;
    @XmlElement(required = true)
    protected String password;
    protected byte[] profilepic;
    protected String realforename;
    protected String reallastname;
    protected String website;
    protected String detailinfo;

    /**
     * Gets the value of the username property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUsername() {
        return username;
    }

    /**
     * Sets the value of the username property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUsername(String value) {
        this.username = value;
    }

    /**
     * Gets the value of the password property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPassword() {
        return password;
    }

    /**
     * Sets the value of the password property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPassword(String value) {
        this.password = value;
    }

    /**
     * Gets the value of the profilepic property.
     * 
     * @return
     *     possible object is
     *     byte[]
     */
    public byte[] getProfilepic() {
        return profilepic;
    }

    /**
     * Sets the value of the profilepic property.
     * 
     * @param value
     *     allowed object is
     *     byte[]
     */
    public void setProfilepic(byte[] value) {
        this.profilepic = value;
    }

    /**
     * Gets the value of the realforename property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRealforename() {
        return realforename;
    }

    /**
     * Sets the value of the realforename property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRealforename(String value) {
        this.realforename = value;
    }

    /**
     * Gets the value of the reallastname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReallastname() {
        return reallastname;
    }

    /**
     * Sets the value of the reallastname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReallastname(String value) {
        this.reallastname = value;
    }

    /**
     * Gets the value of the website property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWebsite() {
        return website;
    }

    /**
     * Sets the value of the website property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWebsite(String value) {
        this.website = value;
    }

    /**
     * Gets the value of the detailinfo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDetailinfo() {
        return detailinfo;
    }

    /**
     * Sets the value of the detailinfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDetailinfo(String value) {
        this.detailinfo = value;
    }

}
